---
dependencies:
  dio: ^5.4.1
  flutter:
    sdk: flutter
  get_it: ^7.6.7
  mssql_connection: ^1.1.3
  pretty_dio_logger: ^1.3.1
  intl: ^0.19.0
  test: ^1.24.9
description: A new Flutter project.
dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
environment:
  sdk: '>=3.3.1 <4.0.0'
flutter:
  uses-material-design: true
name: diplome
publish_to: none
version: 0.1.0